# input directory containing all query fasta. read fastq must be converted to fasta format.
input_dir: "/scratch/xf3/ls9057/Pmelanocephala/Pm_ONT_30Gb_chunks"

# output directory for storing blast report files (*.blast).
# will be created if it doesn't exist
output_blast_dir: "/scratch/xf3/ls9057/Pmelanocephala/Pm_30Gb_blast"

### BLAST SETTINGS ###
blast_env: "/g/data/xf3/miniconda/envs/blast"
blast_db: "/g/data/xf3/database/nt2024Apr10/nt"
blast_outfmt: "6 qseqid sseqid stitle length qcovs pident qlen qstart qend sstart send sskingdoms sscinames staxids evalue"
perc_identity: "75"
max_target_seqs: "10"
evalue: "1e-5"
